package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"xray-proxya/internal/config"
	"xray-proxya/internal/tune"

	"github.com/spf13/cobra"
)

var autoConfirm bool

var selinuxCmd = &cobra.Command{
	Use:   "selinux",
	Short: "Manage SELinux policies and permissions for Xray-Proxya",
}

var selinuxSetupCmd = &cobra.Command{
	Use:   "setup",
	Short: "Automatically generate and apply SELinux policies via audit2allow",
	Run: func(cmd *cobra.Command, args []string) {
		if !requireRoot() {
			return
		}

		// 1. Check sestatus
		out, err := exec.Command("sestatus").Output()
		if err != nil || !strings.Contains(string(out), "SELinux status:                 enabled") {
			fmt.Println("❌ SELinux is not enabled or sestatus command not found.")
			return
		}

		// 2. Check audit2allow
		if _, err := exec.LookPath("audit2allow"); err != nil {
			fmt.Println("❌ audit2allow not found.")
			fmt.Println("Please install it using: dnf install policycoreutils-python-utils")
			return
		}

		fmt.Println("⚠️  WARNING: SELinux Auto-Setup will temporarily disable SELinux enforcing mode.")
		fmt.Println("During this process (approx. 5-10 seconds), DO NOT run other new or untrusted applications,")
		fmt.Println("as their SELinux violations might be accidentally recorded and permanently allowed.")
		fmt.Println("Please make sure no other heavy background tasks are initializing.")

		if !autoConfirm {
			fmt.Print("\nDo you want to proceed? [y/N]: ")
			reader := bufio.NewReader(os.Stdin)
			response, _ := reader.ReadString('\n')
			response = strings.TrimSpace(strings.ToLower(response))
			if response != "y" && response != "yes" {
				fmt.Println("Aborted.")
				return
			}
		}

		fmt.Println("\n[1/5] Switching SELinux to Permissive mode...")
		if err := exec.Command("setenforce", "0").Run(); err != nil {
			fmt.Printf("❌ Failed to set permissive mode: %v\n", err)
			return
		}
		// Ensure we switch back even if panicked or aborted
		defer func() {
			fmt.Println("[5/5] Restoring SELinux to Enforcing mode...")
			exec.Command("setenforce", "1").Run()
			fmt.Println("\n🎉 SELinux setup completed!")
		}()

		fmt.Println("[2/5] Triggering Xray-Proxya high-privilege behaviors...")
		// Restart service to trigger network binding and gateway rules
		if err := exec.Command("systemctl", "restart", "xray-proxya").Run(); err != nil {
			fmt.Printf("⚠️  Failed to restart systemd service (it may not be configured yet): %v\n", err)
		}

		// Re-apply tuning if a saved state exists
		stateFile := filepath.Join(config.GetConfigDir(), ".tune_state")
		if stateBytes, err := os.ReadFile(stateFile); err == nil {
			profileName := strings.TrimSpace(string(stateBytes))
			if profile, ok := tune.GetProfile(profileName); ok {
				fmt.Printf("      -> Triggering tune profile: %s\n", profileName)
				tune.ApplyProfile(profile)
			}
		}

		fmt.Println("[3/5] Waiting for audit logs to flush (5s)...")
		time.Sleep(5 * time.Second)

		fmt.Println("[4/5] Generating and installing SELinux policy module...")
		// Generate policy from audit logs
		grepCmd := exec.Command("grep", "-E", "xray|xray-proxya", "/var/log/audit/audit.log")
		auditCmd := exec.Command("audit2allow", "-M", "xray_proxya")
		
		pipe, _ := grepCmd.StdoutPipe()
		auditCmd.Stdin = pipe
		
		_ = grepCmd.Start()
		_ = auditCmd.Run()
		_ = grepCmd.Wait()
		pipe.Close()

		if _, err := os.Stat("xray_proxya.pp"); err == nil {
			fmt.Println("      -> Installing generated policy module 'xray_proxya.pp'...")
			if out, err := exec.Command("semodule", "-i", "xray_proxya.pp").CombinedOutput(); err != nil {
				fmt.Printf("❌ Failed to install SELinux module: %v\n", err)
				fmt.Printf("   Error details:\n%s\n", string(out))
			} else {
				fmt.Println("✅ SELinux module installed successfully.")
			}
			// Cleanup temporary files generated by audit2allow
			os.Remove("xray_proxya.pp")
			os.Remove("xray_proxya.te")
		} else {
			fmt.Println("⚠️  No SELinux violations detected for xray-proxya. No policy was generated.")
			fmt.Println("      (If things aren't working, try generating traffic or checking port bindings)")
		}
	},
}

func init() {
	selinuxSetupCmd.Flags().BoolVarP(&autoConfirm, "yes", "y", false, "Skip confirmation prompt")
	selinuxCmd.AddCommand(selinuxSetupCmd)
	rootCmd.AddCommand(selinuxCmd)
}
