#!/bin/bash

# ==================================================
# Xray-Proxya Manager
# ==================================================

# --- 用户可配置变量 ---
VMESS_CIPHER="aes-128-gcm"
SS_CIPHER="aes-256-gcm"
# --------------------

CONF_DIR="/etc/xray-proxya"
CONF_FILE="$CONF_DIR/config.env"
ROTATOR_CONF="$CONF_DIR/rotator.env"
XRAY_BIN="/usr/local/bin/xray-proxya-core/xray"
XRAY_DIR="/usr/local/bin/xray-proxya-core"
SERVICE_FILE="/etc/systemd/system/xray-proxya.service"
ROTATOR_SERVICE="/etc/systemd/system/xray-ipv6-rotate.service"
ROTATOR_BIN="/usr/local/bin/xray-ipv6-rotator"
JSON_FILE="$XRAY_DIR/config.json"
LOG_IPV6="/var/log/xray-ipv6.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}❌ 错误: 需要 root 权限${NC}"
        exit 1
    fi
}

install_deps() {
    echo -e "${BLUE}📦 安装依赖 (curl, jq, python3)...${NC}"
    apt-get update -qq >/dev/null
    apt-get install -y curl jq unzip openssl python3 >/dev/null 2>&1
}

generate_random() {
    local length=$1
    openssl rand -base64 $((length * 2)) | tr -dc 'a-zA-Z0-9' | head -c $length
}

check_status() {
    # Xray 状态
    if systemctl is-active --quiet xray-proxya; then
        echo -e "🟢 Xray 服务: ${GREEN}运行中${NC}"
    else
        echo -e "🔴 Xray 服务: ${RED}未运行${NC}"
    fi

    # 轮换器状态
    if systemctl is-active --quiet xray-ipv6-rotate; then
        echo -e "🟢 IPv6 轮换: ${GREEN}运行中${NC}"
        # 读取最后一条日志
        if [ -f "$LOG_IPV6" ]; then
            local last_log=$(tail -n 1 "$LOG_IPV6")
            echo -e "   ➥ 最新 IP: ${YELLOW}${last_log##* }${NC}"
        fi
    else
        echo -e "⚪ IPv6 轮换: 未启用"
    fi
}

download_core() {
    echo -e "${BLUE}⬇️  获取 Xray-core...${NC}"
    LATEST_URL=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r '.assets[] | select(.name=="Xray-linux-64.zip") | .browser_download_url')
    if [ -z "$LATEST_URL" ]; then echo -e "${RED}❌ 下载失败${NC}"; return 1; fi

    systemctl stop xray-proxya 2>/dev/null
    mkdir -p "$XRAY_DIR"
    curl -L -o /tmp/xray.zip "$LATEST_URL"
    unzip -o /tmp/xray.zip -d "$XRAY_DIR" >/dev/null 2>&1
    rm /tmp/xray.zip
    chmod +x "$XRAY_BIN"
}

generate_config() {
    local vmess_p=$1; local vless_p=$2; local ss_p=$3; local uuid=$4
    local vmess_path=$5; local vless_path=$6
    local enc_key=$7; local dec_key=$8; local ss_pass=$9; local ss_method=${10}

    cat > "$JSON_FILE" <<EOF
{
  "log": { "loglevel": "warning" },
  "inbounds": [
    {
      "tag": "vmess-in", "port": $vmess_p, "protocol": "vmess",
      "settings": { "clients": [ { "id": "$uuid", "level": 0 } ] },
      "streamSettings": { "network": "ws", "wsSettings": { "path": "$vmess_path" } }
    },
    {
      "tag": "vless-enc-in", "port": $vless_p, "protocol": "vless",
      "settings": { "clients": [ { "id": "$uuid", "level": 0 } ], "decryption": "$dec_key" },
      "streamSettings": { "network": "xhttp", "xhttpSettings": { "path": "$vless_path" } }
    },
    {
      "tag": "shadowsocks-in", "port": $ss_p, "protocol": "shadowsocks",
      "settings": { "method": "$ss_method", "password": "$ss_pass", "network": "tcp,udp" }
    }
  ],
  "outbounds": [ { "protocol": "freedom" } ]
}
EOF
}

create_service() {
    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Xray-Proxya Service
After=network.target

[Service]
User=root
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=true
ExecStart=$XRAY_BIN run -c $JSON_FILE
Restart=on-failure
RestartPreventExitStatus=23
LimitNPROC=10000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable xray-proxya >/dev/null 2>&1
    systemctl restart xray-proxya
}

# --- IPv6 轮换模块 ---

generate_rotator_script() {
    # 生成 Python 辅助脚本用于 IP 计算 (更健壮)
    # 轮换器主脚本
    cat > "$ROTATOR_BIN" <<'EOF'
#!/bin/bash
# Xray IPv6 Rotator
# Auto-generated by Xray-Proxya

CONF_FILE="/etc/xray-proxya/rotator.env"
LOG_FILE="/var/log/xray-ipv6.log"

if [ ! -f "$CONF_FILE" ]; then echo "No config"; exit 1; fi
source "$CONF_FILE"

# 清空旧日志
echo "--- Service Started $(date) ---" > "$LOG_FILE"

# 信号捕获：退出时清理规则
cleanup() {
    echo "Stopping rotation, cleaning up..." >> "$LOG_FILE"
    # 删除 SNAT 规则
    if [ ! -z "$CURRENT_IP" ]; then
        ip6tables -t nat -D POSTROUTING -s "$CIDR" -j SNAT --to-source "$CURRENT_IP" 2>/dev/null
    fi
    # 删除 Local 路由
    ip route del local "$CIDR" dev lo 2>/dev/null
    exit 0
}
trap cleanup SIGTERM SIGINT

# 1. 添加 AnyIP 路由 (防止回程丢包)
echo "Adding AnyIP route for $CIDR" >> "$LOG_FILE"
ip route add local "$CIDR" dev lo 2>/dev/null

CURRENT_IP=""

while true; do
    # 2. 计算新 IP (使用 Python 处理 CIDR)
    NEW_IP=$(python3 -c "import ipaddress, random; net = ipaddress.IPv6Network('$CIDR'); print(net[random.randint(1, net.num_addresses - 1)])")
    
    if [ -z "$NEW_IP" ]; then
        echo "Error generating IP" >> "$LOG_FILE"
        sleep 60
        continue
    fi

    # 3. 添加新规则 (插入到最前面)
    # 仅针对 TCP/UDP 且非本地回环的出站流量
    ip6tables -t nat -I POSTROUTING 1 -s "$CIDR" -j SNAT --to-source "$NEW_IP"
    
    # 4. 记录日志
    echo "$(date '+%Y-%m-%d %H:%M:%S') Rotated to: $NEW_IP" >> "$LOG_FILE"

    # 5. 删除旧规则 (如果存在)
    if [ ! -z "$CURRENT_IP" ]; then
        ip6tables -t nat -D POSTROUTING -s "$CIDR" -j SNAT --to-source "$CURRENT_IP" 2>/dev/null
    fi
    
    CURRENT_IP="$NEW_IP"

    # 6. 等待间隔 (转换分钟为秒)
    sleep $((INTERVAL * 60))
done
EOF
    chmod +x "$ROTATOR_BIN"

    # 生成 Systemd 服务
    cat > "$ROTATOR_SERVICE" <<EOF
[Unit]
Description=Xray IPv6 Outbound Rotator
After=network.target xray-proxya.service

[Service]
Type=simple
User=root
ExecStart=$ROTATOR_BIN
ExecStop=/bin/kill -s SIGTERM \$MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
}

configure_ipv6_rotate() {
    echo -e "=== IPv6 轮换配置 ==="
    
    # 检测 IPv6 信息
    echo -e "${BLUE}🔍 检测本机 IPv6 信息...${NC}"
    ip -6 addr show scope global | grep inet6 | awk '{print "   Found: " $2}'
    
    echo -e "\n${YELLOW}⚠️  注意：仅在您拥有路由 IPv6 子网 (如 /64, /80) 时使用。${NC}"
    echo -e "${YELLOW}⚠️  AWS/GCP/Azure 等公有云通常不支持此方式(需 API)。${NC}"
    
    read -p "是否启用 IPv6 轮换? (y/n): " enable_rot
    if [[ "$enable_rot" != "y" ]]; then
        systemctl stop xray-ipv6-rotate 2>/dev/null
        systemctl disable xray-ipv6-rotate 2>/dev/null
        echo -e "已禁用轮换。"
        return
    fi

    echo -e "\n请输入您的 IPv6 CIDR (例如: 2001:db8:abcd::/64)"
    echo -e "建议：输入您拥有的一个子块，不要与主 IP 冲突。"
    read -p "CIDR: " input_cidr
    
    # 简单校验
    if [[ ! "$input_cidr" =~ .*:.*\/[0-9]+ ]]; then
        echo -e "${RED}❌ 格式错误。正确示例: 2001:db8::/64${NC}"
        return
    fi

    read -p "轮换间隔 (分钟，建议 60): " input_interval
    if [[ ! "$input_interval" =~ ^[0-9]+$ ]]; then input_interval=60; fi

    # 生成配置
    mkdir -p "$CONF_DIR"
    echo "CIDR=$input_cidr" > "$ROTATOR_CONF"
    echo "INTERVAL=$input_interval" >> "$ROTATOR_CONF"

    # 生成并启动
    generate_rotator_script
    systemctl enable xray-ipv6-rotate >/dev/null 2>&1
    systemctl restart xray-ipv6-rotate
    
    echo -e "${GREEN}✅ 轮换服务已启动！${NC}"
    echo -e "CIDR: $input_cidr | 间隔: ${input_interval}m"
    echo -e "日志: tail -f $LOG_IPV6"
}

# --- 常规安装流程 ---

install_xray() {
    echo -e "=== 安装向导 ==="
    echo -e "加密配置: VMess [${YELLOW}$VMESS_CIPHER${NC}] | SS [${YELLOW}$SS_CIPHER${NC}]"
    
    read -p "VMess 端口 (${vmessp:-8081}): " port_vm; PORT_VMESS=${port_vm:-${vmessp:-8081}}
    read -p "VLESS 端口 (${vlessp:-8082}): " port_vl; PORT_VLESS=${port_vl:-${vlessp:-8082}}
    read -p "SS    端口 (${ssocks:-8083}): " port_ss; PORT_SS=${port_ss:-${ssocks:-8083}}

    for p in $PORT_VMESS $PORT_VLESS $PORT_SS; do
        if ss -lnt | grep -q ":$p "; then echo -e "${RED}⚠️ $p 占用${NC}"; return; fi
    done

    install_deps
    download_core

    echo -e "${BLUE}🔑 生成密钥...${NC}"
    UUID=$("$XRAY_BIN" uuid)
    PATH_VM="/$(openssl rand -hex 12)"
    PATH_VL="/$(openssl rand -hex 12)"
    PASS_SS=$(generate_random 24)
    
    RAW_ENC_OUT=$("$XRAY_BIN" vlessenc)
    DEC_KEY=$(echo "$RAW_ENC_OUT" | grep -A 5 "Authentication: ML-KEM-768" | grep '"decryption":' | cut -d '"' -f 4)
    ENC_KEY=$(echo "$RAW_ENC_OUT" | grep -A 5 "Authentication: ML-KEM-768" | grep '"encryption":' | cut -d '"' -f 4)

    if [ -z "$DEC_KEY" ]; then echo -e "${RED}❌ 密钥失败${NC}"; return 1; fi

    mkdir -p "$CONF_DIR"
    cat > "$CONF_FILE" <<EOF
PORT_VMESS=$PORT_VMESS
PORT_VLESS=$PORT_VLESS
PORT_SS=$PORT_SS
UUID=$UUID
PATH_VM=$PATH_VM
PATH_VL=$PATH_VL
PASS_SS=$PASS_SS
ENC_KEY=$ENC_KEY
DEC_KEY=$DEC_KEY
CFG_VMESS_CIPHER=$VMESS_CIPHER
CFG_SS_CIPHER=$SS_CIPHER
EOF

    generate_config "$PORT_VMESS" "$PORT_VLESS" "$PORT_SS" "$UUID" "$PATH_VM" "$PATH_VL" "$ENC_KEY" "$DEC_KEY" "$PASS_SS" "$SS_CIPHER"
    create_service

    echo -e "${GREEN}✅ 安装完成${NC}"
    show_links
}

format_ip() {
    local ip=$1
    if [[ "$ip" =~ .*:.* ]]; then echo "[$ip]"; else echo "$ip"; fi
}

print_config_group() {
    local ip_addr=$1; local label=$2; if [ -z "$ip_addr" ]; then return; fi
    local fmt_ip=$(format_ip "$ip_addr")
    local vm_cipher=${CFG_VMESS_CIPHER:-$VMESS_CIPHER}
    local ss_cipher=${CFG_SS_CIPHER:-$SS_CIPHER}

    local vmess_json=$(jq -n --arg add "$ip_addr" --arg port "$PORT_VMESS" --arg id "$UUID" --arg path "$PATH_VM" --arg scy "$vm_cipher" \
      '{v:"2", ps:("VMess-" + $scy), add:$add, port:$port, id:$id, aid:"0", scy:$scy, net:"ws", type:"none", host:"", path:$path, tls:""}')
    local vmess_link="vmess://$(echo -n "$vmess_json" | base64 -w 0)"
    local vless_link="vless://$UUID@$fmt_ip:$PORT_VLESS?security=none&encryption=$ENC_KEY&type=xhttp&path=$PATH_VL&headerType=none#VLESS-XHTTP-ENC"
    local ss_auth=$(echo -n "${ss_cipher}:$PASS_SS" | base64 -w 0)
    local ss_link="ss://$ss_auth@$fmt_ip:$PORT_SS#SS-Xray"

    echo -e "\n${BLUE}--- $label ($ip_addr) ---${NC}"
    echo -e "1️⃣  VMess: ${GREEN}$vmess_link${NC}"
    echo -e "2️⃣  VLESS: ${GREEN}$vless_link${NC}"
    echo -e "3️⃣  Shadowsocks: ${GREEN}$ss_link${NC}"
}

show_links() {
    if [ ! -f "$CONF_FILE" ]; then echo -e "${RED}❌ 未安装${NC}"; return; fi
    source "$CONF_FILE"
    echo -e "🔑 UUID: ${YELLOW}$UUID${NC} | 📂 VLESS Path: $PATH_VL"
    
    local ipv4=$(curl -s -4 --max-time 2 https://ipconfig.me || curl -s -4 --max-time 2 https://ifconfig.co)
    local ipv6=$(curl -s -6 --max-time 2 https://ifconfig.co)
    if [ -n "$ipv4" ]; then print_config_group "$ipv4" "IPv4"; fi
    if [ -n "$ipv6" ]; then print_config_group "$ipv6" "IPv6"; fi
    if [ -z "$ipv4" ] && [ -z "$ipv6" ]; then echo -e "${RED}❌ 无法获取IP${NC}"; fi
}

change_ports() {
    if [ ! -f "$CONF_FILE" ]; then echo -e "${RED}未安装${NC}"; return; fi
    source "$CONF_FILE"
    echo -e "当前: V=$PORT_VMESS, VL=$PORT_VLESS, SS=$PORT_SS"
    read -p "新 VMess (回车跳过): " new_vm
    read -p "新 VLESS (回车跳过): " new_vl
    read -p "新 SS    (回车跳过): " new_ss
    [[ ! -z "$new_vm" ]] && sed -i "s/^PORT_VMESS=.*/PORT_VMESS=$new_vm/" "$CONF_FILE"
    [[ ! -z "$new_vl" ]] && sed -i "s/^PORT_VLESS=.*/PORT_VLESS=$new_vl/" "$CONF_FILE"
    [[ ! -z "$new_ss" ]] && sed -i "s/^PORT_SS=.*/PORT_SS=$new_ss/" "$CONF_FILE"
    source "$CONF_FILE"
    local vm_cipher=${CFG_VMESS_CIPHER:-$VMESS_CIPHER}
    local ss_cipher=${CFG_SS_CIPHER:-$SS_CIPHER}
    generate_config "$PORT_VMESS" "$PORT_VLESS" "$PORT_SS" "$UUID" "$PATH_VM" "$PATH_VL" "$ENC_KEY" "$DEC_KEY" "$PASS_SS" "$ss_cipher"
    systemctl restart xray-proxya
    echo -e "${GREEN}✅ 已重启${NC}"
}

maintenance_menu() {
    while true; do
        echo -e "\n=== 服务维护 ==="
        echo "1. 启动 Xray"
        echo "2. 停止 Xray"
        echo "3. 重启 Xray"
        echo "4. 开机自启 Xray"
        echo "5. 取消自启 Xray"
        echo "6. 停止 IPv6 轮换"
        echo "0. 返回"
        read -p "选择: " m_choice
        case "$m_choice" in
            1) systemctl start xray-proxya && echo -e "${GREEN}Done${NC}" ;;
            2) systemctl stop xray-proxya && echo -e "${RED}Stopped${NC}" ;;
            3) systemctl restart xray-proxya && echo -e "${GREEN}Restarted${NC}" ;;
            4) systemctl enable xray-proxya && echo -e "${GREEN}Enabled${NC}" ;;
            5) systemctl disable xray-proxya && echo -e "${YELLOW}Disabled${NC}" ;;
            6) systemctl stop xray-ipv6-rotate; systemctl disable xray-ipv6-rotate; echo -e "${YELLOW}IPv6 轮换已停止${NC}" ;;
            0) return ;;
            *) echo -e "${RED}无效${NC}" ;;
        esac
    done
}

uninstall_xray() {
    read -p "确认卸载? (y/n): " confirm
    if [[ "$confirm" != "y" ]]; then return; fi
    systemctl stop xray-proxya xray-ipv6-rotate
    systemctl disable xray-proxya xray-ipv6-rotate
    rm "$SERVICE_FILE" "$ROTATOR_SERVICE" "$ROTATOR_BIN"
    rm -rf "$XRAY_DIR" "$CONF_DIR"
    systemctl daemon-reload
    echo -e "${GREEN}✅ 已卸载${NC}"
}

check_root
echo -e "${BLUE}Xray-Proxya Manager${NC}"
check_status
echo -e ""
echo "1. 安装 / 重置"
echo "2. 查看链接"
echo "3. 修改端口"
echo "4. 服务维护"
echo "5. 卸载"
echo "6. 配置 IPv6 轮换 (进阶)"
echo "0. 退出"
read -p "选择: " choice

case "$choice" in
    1) install_xray ;;
    2) show_links ;;
    3) change_ports ;;
    4) maintenance_menu ;;
    5) uninstall_xray ;;
    6) configure_ipv6_rotate ;;
    0) exit 0 ;;
    *) echo -e "${RED}无效${NC}" ;;
esac
